PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

CREATE TABLE weapons(name TEXT NOT NULL UNIQUE, valMin INTEGER CHECK(valMin>=0),
valMax INTEGER CHECK(valMax>=0));
INSERT INTO "weapons" VALUES('Twig',NULL,NULL);
INSERT INTO "weapons" VALUES('Wok',NULL,NULL);
INSERT INTO "weapons" VALUES('Staff',NULL,NULL);
INSERT INTO "weapons" VALUES('Skillet',NULL,NULL);
INSERT INTO "weapons" VALUES('Dagger',NULL,NULL);
INSERT INTO "weapons" VALUES('Shortsword',NULL,NULL);
INSERT INTO "weapons" VALUES('Rapier',NULL,NULL);

CREATE TABLE armor(name TEXT NOT NULL UNIQUE, type TEXT,
valMin INTEGER CHECK(valMin>=0), valMax INTEGER CHECK(valMax>=0));

CREATE TABLE mobs(name TEXT NOT NULL UNIQUE,
lvl INTEGER CHECK(lvl>0),
hp  INTEGER CHECK(HP>0),
str INTEGER CHECK(STR>=0),
frt INTEGER CHECK(FRT>=0),
dex INTEGER CHECK(DEX>=0),
expYield INTEGER CHECK(expYield>=0));

INSERT INTO "mobs" VALUES('Rat', 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "mobs" VALUES('Stray Chicken', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "mobs" VALUES('Gnome', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "mobs" VALUES('Wolf', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "mobs" VALUES('Goat', NULL, NULL, NULL, NULL, NULL, NULL);


COMMIT;
